import type { Exercise, WorkoutTemplate } from "@/lib/types";

export const equipmentList = [
  "barbell",
  "plates",
  "squat rack",
  "bench",
  "pull-up bar",
  "functional trainer",
  "kettlebell",
  "dumbbell",
  "rower",
  "treadmill",
  "bike",
  "box",
  "bodyweight"
] as const;

export const exercises: Exercise[] = [
  {
    id: "back-squat",
    name: "Back Squat",
    category: "lower",
    movementPattern: "squat",
    muscleFocus: ["quads", "glutes", "core"],
    equipment: ["barbell", "plates", "squat rack"],
    unilateral: false,
    defaultSets: 4,
    defaultRepMin: 4,
    defaultRepMax: 6,
    substitutionGroup: "heavy-squat"
  },
  {
    id: "bench-press",
    name: "Bench Press",
    category: "upper_push",
    movementPattern: "horizontal press",
    muscleFocus: ["chest", "triceps", "shoulders"],
    equipment: ["barbell", "plates", "bench"],
    unilateral: false,
    defaultSets: 4,
    defaultRepMin: 4,
    defaultRepMax: 8,
    substitutionGroup: "horizontal-press"
  },
  {
    id: "deadlift",
    name: "Deadlift",
    category: "lower",
    movementPattern: "hinge",
    muscleFocus: ["hamstrings", "glutes", "back"],
    equipment: ["barbell", "plates"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 3,
    defaultRepMax: 5,
    substitutionGroup: "heavy-hinge"
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    category: "lower",
    movementPattern: "hinge",
    muscleFocus: ["hamstrings", "glutes", "back"],
    equipment: ["barbell", "plates"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 6,
    defaultRepMax: 10,
    substitutionGroup: "heavy-hinge"
  },
  {
    id: "pull-ups",
    name: "Pull-ups",
    category: "upper_pull",
    movementPattern: "vertical pull",
    muscleFocus: ["lats", "biceps", "upper back"],
    equipment: ["pull-up bar", "bodyweight"],
    unilateral: false,
    defaultSets: 4,
    defaultRepMin: 4,
    defaultRepMax: 10,
    substitutionGroup: "vertical-pull"
  },
  {
    id: "cable-pulldown",
    name: "Cable Pulldown",
    category: "upper_pull",
    movementPattern: "vertical pull",
    muscleFocus: ["lats", "biceps"],
    equipment: ["functional trainer"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "vertical-pull"
  },
  {
    id: "cable-row",
    name: "Cable Row",
    category: "upper_pull",
    movementPattern: "horizontal pull",
    muscleFocus: ["upper back", "lats", "biceps"],
    equipment: ["functional trainer"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "horizontal-pull"
  },
  {
    id: "dumbbell-row",
    name: "Dumbbell Row",
    category: "upper_pull",
    movementPattern: "horizontal pull",
    muscleFocus: ["upper back", "lats"],
    equipment: ["dumbbell", "bench"],
    unilateral: true,
    defaultSets: 4,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "horizontal-pull"
  },
  {
    id: "overhead-press",
    name: "Overhead Press",
    category: "upper_push",
    movementPattern: "vertical press",
    muscleFocus: ["shoulders", "triceps", "core"],
    equipment: ["barbell", "plates"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 5,
    defaultRepMax: 8,
    substitutionGroup: "vertical-press"
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Side Lateral Raise",
    category: "upper_push",
    movementPattern: "shoulder isolation",
    muscleFocus: ["side delts"],
    equipment: ["dumbbell"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    substitutionGroup: "shoulder-accessory"
  },
  {
    id: "face-pull",
    name: "Face Pull",
    category: "upper_pull",
    movementPattern: "rear delt pull",
    muscleFocus: ["rear delts", "upper back"],
    equipment: ["functional trainer"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 12,
    defaultRepMax: 15,
    substitutionGroup: "shoulder-health"
  },
  {
    id: "reverse-fly",
    name: "Dumbbell Reverse Fly",
    category: "upper_pull",
    movementPattern: "rear delt isolation",
    muscleFocus: ["rear delts", "upper back"],
    equipment: ["dumbbell"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    substitutionGroup: "shoulder-health"
  },
  {
    id: "bicep-curl",
    name: "Bicep Curls",
    category: "upper_pull",
    movementPattern: "elbow flexion",
    muscleFocus: ["biceps"],
    equipment: ["dumbbell", "functional trainer"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "arm-curl"
  },
  {
    id: "hammer-curl",
    name: "Hammer Curls",
    category: "upper_pull",
    movementPattern: "elbow flexion",
    muscleFocus: ["biceps", "forearms"],
    equipment: ["dumbbell"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "arm-curl"
  },
  {
    id: "triceps-pressdown",
    name: "Triceps Pressdown",
    category: "upper_push",
    movementPattern: "elbow extension",
    muscleFocus: ["triceps"],
    equipment: ["functional trainer"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    substitutionGroup: "triceps"
  },
  {
    id: "push-ups",
    name: "Push-ups",
    category: "upper_push",
    movementPattern: "horizontal press",
    muscleFocus: ["chest", "triceps", "core"],
    equipment: ["bodyweight"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 25,
    substitutionGroup: "horizontal-press"
  },
  {
    id: "dips",
    name: "Dips",
    category: "upper_push",
    movementPattern: "vertical press",
    muscleFocus: ["triceps", "chest"],
    equipment: ["bodyweight"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 6,
    defaultRepMax: 12,
    substitutionGroup: "press-accessory"
  },
  {
    id: "dumbbell-flyes",
    name: "Dumbbell Flyes",
    category: "upper_push",
    movementPattern: "chest isolation",
    muscleFocus: ["chest", "shoulders"],
    equipment: ["dumbbell", "bench"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 10,
    defaultRepMax: 15,
    substitutionGroup: "chest-accessory"
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    category: "lower",
    movementPattern: "squat",
    muscleFocus: ["quads", "glutes", "core"],
    equipment: ["kettlebell", "dumbbell"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "squat-accessory"
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    category: "lower",
    movementPattern: "single-leg squat",
    muscleFocus: ["quads", "glutes"],
    equipment: ["bench", "dumbbell", "kettlebell"],
    unilateral: true,
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "single-leg"
  },
  {
    id: "lunges",
    name: "Lunges",
    category: "lower",
    movementPattern: "single-leg squat",
    muscleFocus: ["quads", "glutes", "balance"],
    equipment: ["kettlebell", "dumbbell", "bodyweight"],
    unilateral: true,
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "single-leg"
  },
  {
    id: "side-lunges",
    name: "Side Lunges",
    category: "lower",
    movementPattern: "lateral lunge",
    muscleFocus: ["adductors", "glutes", "quads"],
    equipment: ["bodyweight", "kettlebell"],
    unilateral: true,
    defaultSets: 3,
    defaultRepMin: 6,
    defaultRepMax: 10,
    substitutionGroup: "lateral-leg"
  },
  {
    id: "cossack-squat",
    name: "Cossack Squat",
    category: "lower",
    movementPattern: "lateral squat",
    muscleFocus: ["adductors", "hips", "quads"],
    equipment: ["bodyweight", "kettlebell"],
    unilateral: true,
    defaultSets: 3,
    defaultRepMin: 5,
    defaultRepMax: 8,
    substitutionGroup: "lateral-leg"
  },
  {
    id: "single-leg-deadlift",
    name: "Single-leg Deadlift",
    category: "lower",
    movementPattern: "single-leg hinge",
    muscleFocus: ["hamstrings", "glutes", "balance"],
    equipment: ["kettlebell", "dumbbell"],
    unilateral: true,
    defaultSets: 3,
    defaultRepMin: 6,
    defaultRepMax: 10,
    substitutionGroup: "single-leg-hinge"
  },
  {
    id: "kettlebell-deadlift",
    name: "Kettlebell Deadlift",
    category: "lower",
    movementPattern: "hinge",
    muscleFocus: ["hamstrings", "glutes", "back"],
    equipment: ["kettlebell"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "hinge-accessory"
  },
  {
    id: "suitcase-deadlift",
    name: "Kettlebell Suitcase Deadlift",
    category: "lower",
    movementPattern: "offset hinge",
    muscleFocus: ["hamstrings", "glutes", "obliques"],
    equipment: ["kettlebell"],
    unilateral: true,
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "hinge-accessory"
  },
  {
    id: "kettlebell-swing",
    name: "Kettlebell Swings",
    category: "full_body",
    movementPattern: "ballistic hinge",
    muscleFocus: ["glutes", "hamstrings", "conditioning"],
    equipment: ["kettlebell"],
    unilateral: false,
    defaultSets: 4,
    defaultRepMin: 10,
    defaultRepMax: 15,
    substitutionGroup: "power-hinge"
  },
  {
    id: "kettlebell-clean",
    name: "Kettlebell Clean",
    category: "full_body",
    movementPattern: "power pull",
    muscleFocus: ["hips", "upper back", "grip"],
    equipment: ["kettlebell"],
    unilateral: true,
    defaultSets: 3,
    defaultRepMin: 5,
    defaultRepMax: 8,
    substitutionGroup: "full-body-power"
  },
  {
    id: "renegade-row",
    name: "Renegade Rows",
    category: "full_body",
    movementPattern: "anti-rotation row",
    muscleFocus: ["lats", "core", "shoulders"],
    equipment: ["dumbbell"],
    unilateral: true,
    defaultSets: 3,
    defaultRepMin: 6,
    defaultRepMax: 10,
    substitutionGroup: "core-row"
  },
  {
    id: "kettlebell-halo",
    name: "Kettlebell Halo",
    category: "mobility",
    movementPattern: "shoulder mobility",
    muscleFocus: ["shoulders", "upper back", "core"],
    equipment: ["kettlebell"],
    unilateral: false,
    defaultSets: 2,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "shoulder-mobility"
  },
  {
    id: "farmer-carry",
    name: "Farmer Carry",
    category: "core",
    movementPattern: "loaded carry",
    muscleFocus: ["grip", "traps", "core"],
    equipment: ["kettlebell", "dumbbell"],
    unilateral: false,
    defaultSets: 3,
    defaultRepMin: 30,
    defaultRepMax: 60,
    substitutionGroup: "loaded-carry"
  },
  {
    id: "suitcase-march",
    name: "Suitcase Marches",
    category: "core",
    movementPattern: "anti-lateral-flexion",
    muscleFocus: ["obliques", "hips", "grip"],
    equipment: ["kettlebell", "dumbbell"],
    unilateral: true,
    defaultSets: 3,
    defaultRepMin: 20,
    defaultRepMax: 40,
    substitutionGroup: "loaded-carry"
  },
  {
    id: "overhead-march",
    name: "Overhead Marches",
    category: "core",
    movementPattern: "overhead stability",
    muscleFocus: ["shoulders", "core", "hips"],
    equipment: ["kettlebell", "dumbbell"],
    unilateral: true,
    defaultSets: 3,
    defaultRepMin: 20,
    defaultRepMax: 40,
    substitutionGroup: "loaded-carry"
  },
  {
    id: "pallof-press",
    name: "Pallof Press",
    category: "core",
    movementPattern: "anti-rotation",
    muscleFocus: ["obliques", "deep core"],
    equipment: ["functional trainer"],
    unilateral: true,
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "anti-rotation"
  },
  {
    id: "box-step-up",
    name: "Box Step-up",
    category: "lower",
    movementPattern: "single-leg squat",
    muscleFocus: ["quads", "glutes"],
    equipment: ["box", "dumbbell", "kettlebell"],
    unilateral: true,
    defaultSets: 3,
    defaultRepMin: 8,
    defaultRepMax: 12,
    substitutionGroup: "box-work"
  },
  {
    id: "box-jump",
    name: "Box Jump",
    category: "full_body",
    movementPattern: "jump",
    muscleFocus: ["power", "calves", "glutes"],
    equipment: ["box", "bodyweight"],
    unilateral: false,
    defaultSets: 4,
    defaultRepMin: 3,
    defaultRepMax: 5,
    substitutionGroup: "box-work"
  },
  {
    id: "rower-intervals",
    name: "Rower Intervals",
    category: "conditioning",
    movementPattern: "cardio",
    muscleFocus: ["conditioning"],
    equipment: ["rower"],
    unilateral: false,
    defaultSets: 6,
    defaultRepMin: 30,
    defaultRepMax: 60,
    substitutionGroup: "conditioning"
  },
  {
    id: "bike-intervals",
    name: "Bike Intervals",
    category: "conditioning",
    movementPattern: "cardio",
    muscleFocus: ["conditioning"],
    equipment: ["bike"],
    unilateral: false,
    defaultSets: 8,
    defaultRepMin: 30,
    defaultRepMax: 60,
    substitutionGroup: "conditioning"
  },
  {
    id: "treadmill-zone-2",
    name: "Treadmill Zone 2",
    category: "conditioning",
    movementPattern: "cardio",
    muscleFocus: ["aerobic base"],
    equipment: ["treadmill"],
    unilateral: false,
    defaultSets: 1,
    defaultRepMin: 20,
    defaultRepMax: 30,
    substitutionGroup: "conditioning"
  },
  {
    id: "hip-shoulder-mobility",
    name: "Hip and Shoulder Mobility",
    category: "mobility",
    movementPattern: "mobility",
    muscleFocus: ["hips", "shoulders", "thoracic spine"],
    equipment: ["bodyweight", "box"],
    unilateral: false,
    defaultSets: 1,
    defaultRepMin: 5,
    defaultRepMax: 10,
    substitutionGroup: "mobility"
  }
];

export const workoutTemplates: WorkoutTemplate[] = [
  {
    id: "lower-strength-core",
    name: "Lower Strength + Core",
    dayType: "Day 1",
    durationMinutes: 55,
    summary: "Heavy squat pattern, hinge work, single-leg strength, and loaded core.",
    exercises: [
      { exerciseId: "back-squat", orderIndex: 1, block: "main", sets: 4, repMin: 4, repMax: 6, targetRpe: 8, restSeconds: 150 },
      { exerciseId: "romanian-deadlift", orderIndex: 2, block: "main", sets: 3, repMin: 6, repMax: 10, targetRpe: 8, restSeconds: 120 },
      { exerciseId: "lunges", orderIndex: 3, block: "accessory", sets: 3, repMin: 8, repMax: 12, targetRpe: 8, restSeconds: 75 },
      { exerciseId: "cossack-squat", orderIndex: 4, block: "accessory", sets: 3, repMin: 5, repMax: 8, targetRpe: 7, restSeconds: 60 },
      { exerciseId: "pallof-press", orderIndex: 5, block: "accessory", sets: 3, repMin: 8, repMax: 12, targetRpe: 7, restSeconds: 45 },
      { exerciseId: "farmer-carry", orderIndex: 6, block: "conditioning", sets: 3, repMin: 30, repMax: 60, targetRpe: 8, restSeconds: 60 },
      { exerciseId: "rower-intervals", orderIndex: 7, block: "conditioning", sets: 1, repMin: 5, repMax: 8, targetRpe: 7, restSeconds: 0, notes: "Optional easy cooldown or short intervals." }
    ]
  },
  {
    id: "upper-strength",
    name: "Upper Strength",
    dayType: "Day 2",
    durationMinutes: 55,
    summary: "Press, pull, shoulder health, and arms with clear strength progression.",
    exercises: [
      { exerciseId: "bench-press", orderIndex: 1, block: "main", sets: 4, repMin: 4, repMax: 8, targetRpe: 8, restSeconds: 150 },
      { exerciseId: "pull-ups", orderIndex: 2, block: "main", sets: 4, repMin: 4, repMax: 10, targetRpe: 8, restSeconds: 120 },
      { exerciseId: "dumbbell-row", orderIndex: 3, block: "accessory", sets: 4, repMin: 8, repMax: 12, targetRpe: 8, restSeconds: 75 },
      { exerciseId: "overhead-press", orderIndex: 4, block: "main", sets: 3, repMin: 5, repMax: 8, targetRpe: 8, restSeconds: 120 },
      { exerciseId: "face-pull", orderIndex: 5, block: "accessory", sets: 3, repMin: 12, repMax: 15, targetRpe: 7, restSeconds: 45 },
      { exerciseId: "bicep-curl", orderIndex: 6, block: "accessory", sets: 3, repMin: 8, repMax: 12, targetRpe: 8, restSeconds: 45 },
      { exerciseId: "triceps-pressdown", orderIndex: 7, block: "accessory", sets: 3, repMin: 10, repMax: 15, targetRpe: 8, restSeconds: 45 }
    ]
  },
  {
    id: "full-body-power-conditioning",
    name: "Full Body Power + Conditioning",
    dayType: "Day 3",
    durationMinutes: 50,
    summary: "Kettlebell power, bodyweight strength, and intervals.",
    exercises: [
      { exerciseId: "kettlebell-swing", orderIndex: 1, block: "main", sets: 4, repMin: 10, repMax: 15, targetRpe: 8, restSeconds: 75 },
      { exerciseId: "kettlebell-clean", orderIndex: 2, block: "main", sets: 3, repMin: 5, repMax: 8, targetRpe: 7, restSeconds: 75 },
      { exerciseId: "box-step-up", orderIndex: 3, block: "accessory", sets: 3, repMin: 8, repMax: 12, targetRpe: 8, restSeconds: 60 },
      { exerciseId: "push-ups", orderIndex: 4, block: "accessory", sets: 3, repMin: 10, repMax: 25, targetRpe: 8, restSeconds: 60 },
      { exerciseId: "renegade-row", orderIndex: 5, block: "accessory", sets: 3, repMin: 6, repMax: 10, targetRpe: 8, restSeconds: 75 },
      { exerciseId: "bike-intervals", orderIndex: 6, block: "conditioning", sets: 8, repMin: 30, repMax: 60, targetRpe: 8, restSeconds: 60 }
    ]
  },
  {
    id: "hypertrophy-mobility",
    name: "Hypertrophy + Mobility",
    dayType: "Day 4",
    durationMinutes: 60,
    summary: "Moderate volume, movement quality, carries, and mobility.",
    exercises: [
      { exerciseId: "deadlift", orderIndex: 1, block: "main", sets: 3, repMin: 3, repMax: 5, targetRpe: 8, restSeconds: 150 },
      { exerciseId: "dumbbell-flyes", orderIndex: 2, block: "accessory", sets: 3, repMin: 10, repMax: 15, targetRpe: 8, restSeconds: 60 },
      { exerciseId: "single-leg-deadlift", orderIndex: 3, block: "accessory", sets: 3, repMin: 6, repMax: 10, targetRpe: 8, restSeconds: 75 },
      { exerciseId: "cable-row", orderIndex: 4, block: "accessory", sets: 3, repMin: 8, repMax: 12, targetRpe: 8, restSeconds: 75 },
      { exerciseId: "dumbbell-lateral-raise", orderIndex: 5, block: "accessory", sets: 3, repMin: 10, repMax: 15, targetRpe: 8, restSeconds: 45 },
      { exerciseId: "kettlebell-halo", orderIndex: 6, block: "mobility", sets: 2, repMin: 8, repMax: 12, targetRpe: 6, restSeconds: 30 },
      { exerciseId: "suitcase-march", orderIndex: 7, block: "conditioning", sets: 3, repMin: 20, repMax: 40, targetRpe: 8, restSeconds: 60 },
      { exerciseId: "hip-shoulder-mobility", orderIndex: 8, block: "mobility", sets: 1, repMin: 5, repMax: 10, targetRpe: 5, restSeconds: 0 }
    ]
  }
];

export function getExercise(id: string) {
  return exercises.find((exercise) => exercise.id === id);
}

export function getSubstitutions(exerciseId: string) {
  const exercise = getExercise(exerciseId);
  if (!exercise) return [];
  return exercises.filter(
    (candidate) => candidate.substitutionGroup === exercise.substitutionGroup && candidate.id !== exercise.id
  );
}
